# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alex Thissen Weblog Build 1.15.10.1971
email: athissen@xpirit.com
description: > # this means to ignore newlines until "baseurl:"
  Disassembling my brain.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.alexthissen.nl" # the base hostname & protocol for your site
twitter_username: alexthissen
github_username:  alexthissen

# Build settings
markdown: kramdown
